function [ FIXATIONCROSS ] = FixationCross()
global S

FIXATIONCROSS = PTB_OBJECTS.VIDEO.FixationCross(                                           ...
S.TaskParam.FixationCross.Size * S.PTB.Video.Y_total_px                                  , ...
S.TaskParam.FixationCross.Size * S.PTB.Video.Y_total_px * S.TaskParam.FixationCross.Width, ...
S.TaskParam.FixationCross.Color                                                          , ...
S.TaskParam.FixationCross.Position .* [ S.PTB.Video.X_total_px S.PTB.Video.Y_total_px ]    ...
);

FIXATIONCROSS.LinkToWindowPtr(S.PTB.Video.wPtr);
FIXATIONCROSS.AssertReady();

end % function
