function varargout = OpenGUI()
% OpenGUI is the function that creates (or bring to focus) GUI.
% Then, GUI.MODEL.Core() is always called to start each task. It is the
% "main" program.

% debug=1 closes previous figure and reopens it, and send the gui handles
% to base workspace.
debug = 0;

gui_name = [ 'GUI_' project_name() ];


%% Open a singleton figure, or gring the actual into focus.

% Is the GUI already open ?
figPtr = findall(0,'Tag',gui_name);

if ~isempty(figPtr) % Figure exists so brings it to the focus
    
    figure(figPtr);
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%% DEBUG %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if debug
        clc %#ok<UNRCH>
        close(figPtr);
        GUI.VIEW.OpenGUI();
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    
else % Create the figure
    
    rng('default')
    rng('shuffle')
    
    % Create a figure
    figHandle = figure( ...
        'HandleVisibility', 'off',... % close all does not close the figure
        'MenuBar'         , 'none'                   , ...
        'Toolbar'         , 'none'                   , ...
        'Name'            , gui_name                 , ...
        'NumberTitle'     , 'off'                    , ...
        'Units'           , 'Pixels'                 , ...
        'Position'        , [50, 50, 600, 700]       , ...
        'Tag'             , gui_name                 );
    
    figureBGcolor = [0.9 0.9 0.9]; set(figHandle,'Color',figureBGcolor);
    buttonBGcolor = figureBGcolor - 0.1;
    editBGcolor   = [1.0 1.0 1.0];
    
    % Create GUI handles : pointers to access the graphic objects
    handles               = guihandles(figHandle);
    handles.figureBGcolor = figureBGcolor;
    handles.buttonBGcolor = buttonBGcolor;
    handles.editBGcolor   = editBGcolor  ;
    
    
    %% Panel proportions
    
    panelProp.xposP = 0.01; % xposition of panel normalized : from 0 to 1
    panelProp.wP    = 1 - panelProp.xposP * 2;
    
    panelProp.interWidth = 0.01;
    panelProp.vect  = ...
        [0.5 0.75 2 1.5 1 0.75 1.5 ]; % relative proportions of each panel, from bottom to top
    
    panelProp.vectLength    = length(panelProp.vect);
    panelProp.vectTotal     = sum(panelProp.vect);
    panelProp.unitWidth     = ( 1 - (panelProp.interWidth*(panelProp.vectLength + 1)) ) / panelProp.vectTotal ;
    
    panelProp.countP = panelProp.vectLength + 1;
    panelProp.yposP  = @(countP) panelProp.unitWidth*sum(panelProp.vect(1:countP-1)) + panelProp.interWidth *(countP);
    
    
    %% Panel : Subject & Run
    
    p_sr.x = panelProp.xposP;
    p_sr.w = panelProp.wP;
    
    panelProp.countP = panelProp.countP - 1;
    p_sr.y = panelProp.yposP(panelProp.countP);
    p_sr.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_SubjectRun = uipanel(handles.(gui_name),...
        'Title','Subject & Run',...
        'Units', 'Normalized',...
        'Position',[p_sr.x p_sr.y p_sr.w p_sr.h],...
        'BackgroundColor',figureBGcolor);
    
    p_sr = GUI.VIEW.Object_Xpos_Xwidth_dispatcher( p_sr , [1 1 1] , 0.05 );
    p_sr.yposOmain = 0.1;
    p_sr.hOmain    = 0.6;
    p_sr.yposOhdr  = 0.7;
    p_sr.hOhdr     = 0.2;
    
    
    % ---------------------------------------------------------------------
    % Edit : Subject ID
    
    p_sr.count = p_sr.count + 1;
    e_sid.x = p_sr.xpos(p_sr.count);
    e_sid.y = p_sr.yposOmain ;
    e_sid.w = p_sr.xwidth(p_sr.count);
    e_sid.h = p_sr.hOmain;
    handles.edit_SubjectID = uicontrol(handles.uipanel_SubjectRun,...
        'Style','edit',...
        'Units', 'Normalized',...
        'Position',[e_sid.x e_sid.y e_sid.w e_sid.h],...
        'BackgroundColor',editBGcolor,...
        'String','',...
        'Callback',@GUI.VIEW.Callback.edit_SubjectID);
    
    
    % ---------------------------------------------------------------------
    % Text : Subject ID
    
    t_sid.x = p_sr.xpos(p_sr.count);
    t_sid.y = p_sr.yposOhdr ;
    t_sid.w = p_sr.xwidth(p_sr.count);
    t_sid.h = p_sr.hOhdr;
    handles.text_SubjectID = uicontrol(handles.uipanel_SubjectRun,...
        'Style','text',...
        'Units', 'Normalized',...
        'Position',[t_sid.x t_sid.y t_sid.w t_sid.h],...
        'String','Subject ID',...
        'BackgroundColor',figureBGcolor);
    
    
    % ---------------------------------------------------------------------
    % Pushbutton : Check SubjectID data
    
    p_sr.count = p_sr.count + 1;
    b_csidd.x = p_sr.xpos(p_sr.count);
    b_csidd.y = p_sr.yposOmain;
    b_csidd.w = p_sr.xwidth(p_sr.count);
    b_csidd.h = p_sr.hOmain;
    handles.pushbutton_Check_SubjectID_data = uicontrol(handles.uipanel_SubjectRun,...
        'Style','pushbutton',...
        'Units', 'Normalized',...
        'Position',[b_csidd.x b_csidd.y b_csidd.w b_csidd.h],...
        'String','Check SubjectID data',...
        'BackgroundColor',buttonBGcolor,...
        'TooltipString','Display in Command Window the content of data/(SubjectID)',...
        'Callback',@GUI.VIEW.Callback.pushbutton_CheckSubjecIDdata);
    
    
    % ---------------------------------------------------------------------
    % Text : Last file name annoucer
    
    p_sr.count = p_sr.count + 1;
    t_lfna.x = p_sr.xpos(p_sr.count);
    t_lfna.y = p_sr.yposOhdr ;
    t_lfna.w = p_sr.xwidth(p_sr.count);
    t_lfna.h = p_sr.hOhdr;
    handles.text_LastFileNameAnnouncer = uicontrol(handles.uipanel_SubjectRun,...
        'Style','text',...
        'Units', 'Normalized',...
        'Position',[t_lfna.x t_lfna.y t_lfna.w t_lfna.h],...
        'String','Last file name',...
        'BackgroundColor',figureBGcolor,...
        'Visible','Off');
    
    
    % ---------------------------------------------------------------------
    % Text : Last file name
    
    t_lfn.x = p_sr.xpos(p_sr.count);
    t_lfn.y = p_sr.yposOmain ;
    t_lfn.w = p_sr.xwidth(p_sr.count);
    t_lfn.h = p_sr.hOmain;
    handles.text_LastFileName = uicontrol(handles.uipanel_SubjectRun,...
        'Style','text',...
        'Units', 'Normalized',...
        'Position',[t_lfn.x t_lfn.y t_lfn.w t_lfn.h],...
        'String','',...
        'BackgroundColor',figureBGcolor,...
        'Visible','Off');
    
    
    %% Panel : Save mode
    
    p_sm.x = panelProp.xposP;
    p_sm.w = panelProp.wP;
    
    panelProp.countP = panelProp.countP - 1;
    p_sm.y = panelProp.yposP(panelProp.countP);
    p_sm.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_SaveMode = uibuttongroup(handles.(gui_name),...
        'Title','Save mode',...
        'Units', 'Normalized',...
        'Position',[p_sm.x p_sm.y p_sm.w p_sm.h],...
        'BackgroundColor',figureBGcolor);
    
    p_sm = GUI.VIEW.Object_Xpos_Xwidth_dispatcher( p_sm , [1 1] , 0.25 );
    
    % ---------------------------------------------------------------------
    % RadioButton : Save Data
    
    p_sm.count = p_sm.count + 1;
    r_sd.x   = p_sm.xpos(p_sm.count);
    r_sd.y   = 0.1 ;
    r_sd.w   = p_sm.w;
    r_sd.h   = 0.8;
    r_sd.tag = 'radiobutton_SaveData';
    handles.(r_sd.tag) = uicontrol(handles.uipanel_SaveMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_sd.x r_sd.y r_sd.w r_sd.h],...
        'String','Save data',...
        'TooltipString','Save data to : ../data/SubjectID/...',...
        'HorizontalAlignment','Center',...
        'Tag',r_sd.tag,...
        'BackgroundColor',figureBGcolor);
    
    
    % ---------------------------------------------------------------------
    % RadioButton : No save
    
    p_sm.count = p_sm.count + 1;
    r_ns.x   = p_sm.xpos(p_sm.count);
    r_ns.y   = 0.1 ;
    r_ns.w   = p_sm.w;
    r_ns.h   = 0.8;
    r_ns.tag = 'radiobutton_NoSave';
    handles.(r_ns.tag) = uicontrol(handles.uipanel_SaveMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_ns.x r_ns.y r_ns.w r_ns.h],...
        'String','No save',...
        'TooltipString','In Acquisition mode, Save mode must be engaged',...
        'HorizontalAlignment','Center',...
        'Tag',r_ns.tag,...
        'BackgroundColor',figureBGcolor);
    
    
    %% Panel : Eyelink mode
    
    el_shift = 0.25;
    
    p_el.x = panelProp.xposP/2 + el_shift;
    p_el.w = panelProp.wP - el_shift + panelProp.xposP/2;
    
    panelProp.countP = panelProp.countP - 1;
    p_el.y = panelProp.yposP(panelProp.countP);
    p_el.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_EyelinkMode = uibuttongroup(handles.(gui_name),...
        'Title','Eyelink mode',...
        'Units', 'Normalized',...
        'Position',[p_el.x p_el.y p_el.w p_el.h],...
        'BackgroundColor',figureBGcolor,...
        'SelectionChangeFcn',@GUI.VIEW.SelectionChangeFcn.uipanel_EyelinkMode);
    
    
    % ---------------------------------------------------------------------
    % Checkbox : Windowed screen
    
    c_ws.x = panelProp.xposP;
    c_ws.w = el_shift - panelProp.xposP/2;
    
    c_ws.y = panelProp.yposP(panelProp.countP)-0.01 ;
    c_ws.h = p_el.h * 0.3;
    
    handles.checkbox_WindowedScreen = uicontrol(handles.(gui_name),...
        'Style','checkbox',...
        'Units', 'Normalized',...
        'Position',[c_ws.x c_ws.y c_ws.w c_ws.h],...
        'String','Windowed screen',...
        'HorizontalAlignment','Center',...
        'BackgroundColor',figureBGcolor);
    
    
    % ---------------------------------------------------------------------
    % Listbox : Screens
    
    l_sc.x = panelProp.xposP;
    l_sc.w = el_shift - panelProp.xposP;
    
    l_sc.y = c_ws.y + c_ws.h ;
    l_sc.h = p_el.h * 0.6;
    
    handles.listbox_Screens = uicontrol(handles.(gui_name),...
        'Style','listbox',...
        'Units', 'Normalized',...
        'Position',[l_sc.x l_sc.y l_sc.w l_sc.h],...
        'String',{'a' 'b' 'c'},...
        'TooltipString','Select the display mode   PTB : 0 for extended display (over all screens) , 1 for screen 1 , 2 for screen 2 , etc.',...
        'HorizontalAlignment','Center',...
        'CreateFcn',@GUI.Listbox_Screens_CreateFcn);
    
    
    % ---------------------------------------------------------------------
    % Text : ScreenMode
    
    t_sm.x = panelProp.xposP;
    t_sm.w = el_shift - panelProp.xposP;
    
    t_sm.y = l_sc.y + l_sc.h ;
    t_sm.h = p_el.h * 0.15;
    
    handles.text_ScreenMode = uicontrol(handles.(gui_name),...
        'Style','text',...
        'Units', 'Normalized',...
        'Position',[t_sm.x t_sm.y t_sm.w t_sm.h],...
        'String','Screen mode selection',...
        'TooltipString','Output of Screen(''Screens'')   Use ''Screen Screens?'' in Command window for help',...
        'HorizontalAlignment','Center',...
        'BackgroundColor',figureBGcolor);
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    p_el_up.nbO    = 6; % Number of objects
    p_el_up.w     = 1/(p_el_up.nbO + 1); % Object width
    p_el_up.count = 0; % Object counter
    p_el_up.xpos  = @(count) p_el_up.w/(p_el_up.nbO+1)*count + (count-1)*p_el_up.w;
    p_el_up.y      = 0.6;
    p_el_up.h      = 0.3;
    
    % ---------------------------------------------------------------------
    % RadioButton : Eyelink ON
    
    p_el_up.count = p_el_up.count + 1;
    r_elon.x   = p_el_up.xpos(p_el_up.count);
    r_elon.y   = p_el_up.y ;
    r_elon.w   = p_el_up.w;
    r_elon.h   = p_el_up.h;
    r_elon.tag = 'radiobutton_EyelinkOn';
    handles.(r_elon.tag) = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_elon.x r_elon.y r_elon.w r_elon.h],...
        'String','On',...
        'HorizontalAlignment','Center',...
        'Tag',r_elon.tag,...
        'BackgroundColor',figureBGcolor,...
        'Visible','On');
    
    
    % ---------------------------------------------------------------------
    % RadioButton : Eyelink OFF
    
    p_el_up.count = p_el_up.count + 1;
    r_eloff.x   = p_el_up.xpos(p_el_up.count);
    r_eloff.y   = p_el_up.y ;
    r_eloff.w   = p_el_up.w;
    r_eloff.h   = p_el_up.h;
    r_eloff.tag = 'radiobutton_EyelinkOff';
    handles.(r_eloff.tag) = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_eloff.x r_eloff.y r_eloff.w r_eloff.h],...
        'String','Off',...
        'HorizontalAlignment','Center',...
        'Tag',r_eloff.tag,...
        'BackgroundColor',figureBGcolor,...
        'Visible','On');
    
    
    % ---------------------------------------------------------------------
    % Checkbox : Parallel port
    
    p_el_up.count = p_el_up.count + 1;
    c_pp.x = p_el_up.xpos(p_el_up.count);
    c_pp.y = p_el_up.y ;
    c_pp.w = p_el_up.w*2;
    c_pp.h = p_el_up.h;
    handles.checkbox_ParPort = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','checkbox',...
        'Units', 'Normalized',...
        'Position',[c_pp.x c_pp.y c_pp.w c_pp.h],...
        'String','Parallel port',...
        'HorizontalAlignment','Center',...
        'TooltipString','Send messages via parallel port : useful for Eyelink',...
        'BackgroundColor',figureBGcolor,...
        'Value',0,...
        'Callback',@GUI.Checkbox_ParPort_Callback,...
        'CreateFcn',@GUI.Checkbox_ParPort_Callback,...
        'Visible','Off');
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    p_el_dw.nbO    = 4.5; % Number of objects
    p_el_dw.w     = 1/(p_el_dw.nbO + 1); % Object width
    p_el_dw.count = 0; % Object counter
    p_el_dw.xpos  = @(count) p_el_dw.w/(p_el_dw.nbO+1)*count + (count-1)*p_el_dw.w;
    p_el_dw.y      = 0.1;
    p_el_dw.h      = 0.4 ;
    
    
    % ---------------------------------------------------------------------
    % Pushbutton : Eyelink Initialize
    
    p_el_dw.count = p_el_dw.count + 1;
    b_init.x = p_el_dw.xpos(p_el_dw.count);
    b_init.y = p_el_dw.y ;
    b_init.w = p_el_dw.w;
    b_init.h = p_el_dw.h;
    handles.pushbutton_Initialize = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','pushbutton',...
        'Units', 'Normalized',...
        'Position',[b_init.x b_init.y b_init.w b_init.h],...
        'String','Initialize',...
        'BackgroundColor',buttonBGcolor,...
        'Callback','Eyelink.Initialize');
    
    % ---------------------------------------------------------------------
    % Pushbutton : Eyelink IsConnected
    
    p_el_dw.count = p_el_dw.count + 1;
    b_isco.x = p_el_dw.xpos(p_el_dw.count);
    b_isco.y = p_el_dw.y ;
    b_isco.w = p_el_dw.w;
    b_isco.h = p_el_dw.h;
    handles.pushbutton_IsConnected = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','pushbutton',...
        'Units', 'Normalized',...
        'Position',[b_isco.x b_isco.y b_isco.w b_isco.h],...
        'String','IsConnected',...
        'BackgroundColor',buttonBGcolor,...
        'Callback','Eyelink.IsConnected');
    
    
    % ---------------------------------------------------------------------
    % Pushbutton : Eyelink Calibration
    
    p_el_dw.count = p_el_dw.count + 1;
    b_cal.x   = p_el_dw.xpos(p_el_dw.count);
    b_cal.y   = p_el_dw.y ;
    b_cal.w   = p_el_dw.w;
    b_cal.h   = p_el_dw.h;
    b_cal.tag = 'pushbutton_EyelinkCalibration';
    handles.(b_cal.tag) = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','pushbutton',...
        'Units', 'Normalized',...
        'Position',[b_cal.x b_cal.y b_cal.w b_cal.h],...
        'String','Calibration',...
        'BackgroundColor',buttonBGcolor,...
        'Tag',b_cal.tag,...
        'Callback',@GUI.VIEW.Callback.pushbutton_EyelinkCalibration);
    
    
    % ---------------------------------------------------------------------
    % Pushbutton : Download EL files according to the SubjectID
    
    p_el_dw.count = p_el_dw.count + 1;
    b_cal.x   = p_el_dw.xpos(p_el_dw.count);
    b_cal.y   = p_el_dw.y ;
    b_cal.w   = p_el_dw.w*1.5;
    b_cal.h   = p_el_dw.h;
    b_cal.tag = 'pushbutton_DownloadELfiles';
    handles.(b_cal.tag) = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','pushbutton',...
        'Units', 'Normalized',...
        'Position',[b_cal.x b_cal.y b_cal.w b_cal.h],...
        'String','Download files',...
        'BackgroundColor',buttonBGcolor*0.9,...
        'Tag',b_cal.tag,...
        'Callback',@GUI.VIEW.Callback.pushbutton_DownloadELfiles);
    
    
    % ---------------------------------------------------------------------
    % Pushbutton : Eyelink force shutdown
    
    b_fsd.x = c_pp.x + c_pp.h;
    b_fsd.y = p_el_up.y ;
    b_fsd.w = p_el_dw.w*1.50;
    b_fsd.h = p_el_dw.h;
    handles.pushbutton_ForceShutDown = uicontrol(handles.uipanel_EyelinkMode,...
        'Style','pushbutton',...
        'Units', 'Normalized',...
        'Position',[b_fsd.x b_fsd.y b_fsd.w b_fsd.h],...
        'String','ForceShutDown',...
        'BackgroundColor',buttonBGcolor,...
        'Callback','Eyelink.ForceShutDown');
    
    
    %% Panel : Task
    
    p_task.x = panelProp.xposP;
    p_task.w = panelProp.wP ;
    
    %----------------------------------------------------------------------
    % 1 => not sinc with TR
    
    panelProp.countP = panelProp.countP - 1;
    p_task.y = panelProp.yposP(panelProp.countP);
    p_task.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_Task = uibuttongroup(handles.(gui_name),...
        'Title','Task',...
        'Units', 'Normalized',...
        'Position',[p_task.x p_task.y p_task.w p_task.h],...
        'BackgroundColor',figureBGcolor);
    
    b_Calib.x   = 0.10;
    b_Calib.w   = 0.40;
    b_Calib.y   = 0.45;
    b_Calib.h   = 0.50;
    b_Calib.tag = 'pushbutton_Calibration';
    handles.(b_Calib.tag) = uicontrol(handles.uipanel_Task          ,...
        'Style'          , 'pushbutton'                             ,...
        'Units'          , 'Normalized'                             ,...
        'Position'       , [b_Calib.x b_Calib.y b_Calib.w b_Calib.h],...
        'String'         , 'Calibration'                            ,...
        'BackgroundColor', buttonBGcolor                            ,...
        'Tag'            , b_Calib.tag                              ,...
        'Callback'       , @GUI.MODEL.Core                              ,...
        'TooltipString'  , 'Maximum strengh calibration'            );
    
    b_Nut.x   = 0.50;
    b_Nut.w   = 0.40;
    b_Nut.y   = 0.45;
    b_Nut.h   = 0.50;
    b_Nut.tag = 'pushbutton_Nutcracker';
    handles.(b_Nut.tag) = uicontrol(handles.uipanel_Task    ,...
        'Style'          , 'pushbutton'                     ,...
        'Units'          , 'Normalized'                     ,...
        'Position'       , [b_Nut.x b_Nut.y b_Nut.w b_Nut.h],...
        'String'         , 'Nutcracker'                     ,...
        'BackgroundColor', buttonBGcolor                    ,...
        'Tag'            , b_Nut.tag                        ,...
        'Callback'       , @GUI.MODEL.Core                      ,...
        'TooltipString'  , 'fMRI task'                      );
    
    e_Max.x   = 0.10;
    e_Max.w   = 0.80;
    e_Max.y   = 0.05;
    e_Max.h   = 0.40;
    e_Max.tag = 'edit_MaxStrength';
    handles.(e_Max.tag) = uicontrol(handles.uipanel_Task    ,...
        'Style'          , 'edit'                           ,...
        'Units'          , 'Normalized'                     ,...
        'Position'       , [e_Max.x e_Max.y e_Max.w e_Max.h],...
        'String'         , '320'                            ,...
        'BackgroundColor', editBGcolor                      ,...
        'Tag'            , e_Max.tag                        ,...
        'Callback'       , @GUI.MODEL.Core                      ,...
        'TooltipString'  , 'in Newton (N)'                  );
    
    
    %% Panel : device input
    
    p_device.x = panelProp.xposP;
    p_device.w = 0.3;
    
    panelProp.countP = panelProp.countP - 1;
    p_device.y = panelProp.yposP(panelProp.countP);
    p_device.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_Device = uibuttongroup(handles.(gui_name),...
        'Title','Device selection',...
        'Units', 'Normalized',...
        'Position',[p_device.x p_device.y p_device.w p_device.h],...
        'BackgroundColor',figureBGcolor,...
        'SelectionChangeFcn',@GUI.VIEW.SelectionChangeFcn.uipanel_Device);
    
    % ---------------------------------------------------------------------
    % RadioButton : Nutcracker == joystick IO
    
    r_nut.x   = 0.05;
    r_nut.y   = 0.70;
    r_nut.w   = 0.90;
    r_nut.h   = 0.10;
    r_nut.tag = 'radiobutton_nutcracker';
    handles.(r_nut.tag) = uicontrol(handles.uipanel_Device,...
        'Style','radiobutton'                             ,...
        'Units', 'Normalized'                             ,...
        'Position',[r_nut.x r_nut.y r_nut.w r_nut.h]      ,...
        'String','Nutcracker'                             ,...
        'HorizontalAlignment','Center'                    ,...
        'Tag',r_nut.tag                                   ,...
        'BackgroundColor',figureBGcolor                   );
    
    
    % ---------------------------------------------------------------------
    % RadioButton : Mouse (for debugging)
    
    r_mouse.x   = r_nut.x;
    r_mouse.y   = 1 - r_nut.y;
    r_mouse.w   = r_nut.w;
    r_mouse.h   = r_nut.h;
    r_mouse.tag = 'radiobutton_mouse';
    handles.(r_mouse.tag) = uicontrol(handles.uipanel_Device,...
        'Style','radiobutton'                               ,...
        'Units', 'Normalized'                               ,...
        'Position',[r_mouse.x r_mouse.y r_mouse.w r_mouse.h],...
        'String','Mouse'                                    ,...
        'HorizontalAlignment','Center'                      ,...
        'Tag',r_mouse.tag                                   ,...
        'BackgroundColor',figureBGcolor                     );
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Panel : Joystick online display
    
    p_joystick.x = p_device.x + p_device.w;
    p_joystick.y = p_device.y;
    p_joystick.w = 1 - p_device.w - p_device.x;
    p_joystick.h = p_device.h;
    handles.uipanel_Joystick = uipanel(handles.(gui_name),...
        'Title','Joystick',...
        'Units', 'Normalized',...
        'Position',[ p_joystick.x p_joystick.y p_joystick.w p_joystick.h ],...
        'BackgroundColor',figureBGcolor);
    
    
    b_stream.x   = 0.10;
    b_stream.w   = 0.20;
    b_stream.y   = 0.20;
    b_stream.h   = 1 - b_stream.y*2;
    b_stream.tag = 'toggle_Stream';
    handles.(b_stream.tag) = uicontrol(handles.uipanel_Joystick,...
        'Style'          , 'toggle'                         ,...
        'Units'          , 'Normalized'                     ,...
        'Position'       , [b_stream.x b_stream.y b_stream.w b_stream.h],...
        'String'         , 'Display'                        ,...
        'BackgroundColor', buttonBGcolor                    ,...
        'Tag'            , b_stream.tag                     ,...
        'Callback'       , @GUI.VIEW.Callback.toggle_JoystickStream,...
        'TooltipString'  , 'Live display of the joystick values');
    
    
    a_joystick.x   = b_stream.x*2 + b_stream.w;
    a_joystick.w   = 1 - a_joystick.x - b_stream.x;
    a_joystick.y   = b_stream.y;
    a_joystick.h   = 1- a_joystick.y;
    
    handles.axes_Joystick = axes(handles.uipanel_Joystick,...
        'Units'          , 'Normalized'                     ,...
        'Position'       , [a_joystick.x a_joystick.y a_joystick.w a_joystick.h]);
    GUI.VIEW.setAxesJoystickStream( handles ); % wrapper, because used several times
    
    
    %% Panel : Operation mode
    
    p_op.x = panelProp.xposP;
    p_op.w = panelProp.wP;
    
    panelProp.countP = panelProp.countP - 1;
    p_op.y = panelProp.yposP(panelProp.countP);
    p_op.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_OperationMode = uibuttongroup(handles.(gui_name),...
        'Title','Operation mode',...
        'Units', 'Normalized',...
        'Position',[p_op.x p_op.y p_op.w p_op.h],...
        'BackgroundColor',figureBGcolor);
    
    p_op = GUI.VIEW.Object_Xpos_Xwidth_dispatcher( p_op , [1 1 1] , 0.1 );
    
    % ---------------------------------------------------------------------
    % RadioButton : Acquisition
    
    p_op.count = p_op.count + 1;
    r_aq.x = p_op.xpos(p_op.count);
    r_aq.y = 0.1 ;
    r_aq.w = p_op.w;
    r_aq.h = 0.8;
    r_aq.tag = 'radiobutton_Acquisition';
    handles.(r_aq.tag) = uicontrol(handles.uipanel_OperationMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_aq.x r_aq.y r_aq.w r_aq.h],...
        'String','Acquisition',...
        'TooltipString','Save data, execute full script',...
        'HorizontalAlignment','Center',...
        'Tag',r_aq.tag,...
        'BackgroundColor',figureBGcolor);
    
    
    % ---------------------------------------------------------------------
    % RadioButton : FastDebug
    
    p_op.count = p_op.count + 1;
    r_fd.x   = p_op.xpos(p_op.count);
    r_fd.y   = 0.1 ;
    r_fd.w   = p_op.w;
    r_fd.h   = 0.8;
    r_fd.tag = 'radiobutton_FastDebug';
    handles.radiobutton_FastDebug = uicontrol(handles.uipanel_OperationMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_fd.x r_fd.y r_fd.w r_fd.h],...
        'String','FastDebug',...
        'TooltipString','Don''t save data, run the scripts very fast',...
        'HorizontalAlignment','Center',...
        'Tag',r_fd.tag,...
        'BackgroundColor',figureBGcolor);
    
    
    % ---------------------------------------------------------------------
    % RadioButton : RealisticDebug
    
    p_op.count = p_op.count + 1;
    r_rd.x   = p_op.xpos(p_op.count);
    r_rd.y   = 0.1 ;
    r_rd.w   = p_op.w;
    r_rd.h   = 0.8;
    r_rd.tag = 'radiobutton_RealisticDebug';
    handles.(r_rd.tag) = uicontrol(handles.uipanel_OperationMode,...
        'Style','radiobutton',...
        'Units', 'Normalized',...
        'Position',[r_rd.x r_rd.y r_rd.w r_rd.h],...
        'String','RealisticDebug',...
        'TooltipString','ODon''t save data, run the scripts ~normal speed',...
        'HorizontalAlignment','Center',...
        'Tag',r_rd.tag,...
        'BackgroundColor',figureBGcolor);
    
    
    %% Panel : record movie
    
    p_movie.x = panelProp.xposP;
    p_movie.w = panelProp.wP;
    
    panelProp.countP = panelProp.countP - 1;
    p_movie.y = panelProp.yposP(panelProp.countP);
    p_movie.h = panelProp.unitWidth*panelProp.vect(panelProp.countP);
    
    handles.uipanel_Movie = uibuttongroup(handles.(gui_name),...
        'Title','Movie recording',...
        'Units', 'Normalized',...
        'Position',[p_movie.x p_movie.y p_movie.w p_movie.h],...
        'BackgroundColor',figureBGcolor);
    
    p_movie = GUI.VIEW.Object_Xpos_Xwidth_dispatcher( p_movie , [1 1] , 0.25 );
    
    % ---------------------------------------------------------------------
    % RadioButton : Nutcracker == joystick IO
    
    p_movie.count = p_movie.count + 1;
    r_movie_off.x   = p_movie.xpos(p_movie.count);
    r_movie_off.y   = 0.1 ;
    r_movie_off.w   = p_movie.w;
    r_movie_off.h   = 0.8;
    r_movie_off.tag = 'radiobutton_movie_off';
    handles.(r_movie_off.tag) = uicontrol(handles.uipanel_Movie,...
        'Style','radiobutton'                             ,...
        'Units', 'Normalized'                             ,...
        'Position',[r_movie_off.x r_movie_off.y r_movie_off.w r_movie_off.h],...
        'String','Off       '                             ,...
        'HorizontalAlignment','Center'                    ,...
        'Tag',r_movie_off.tag                             ,...
        'BackgroundColor',figureBGcolor                   );
    
    
    % ---------------------------------------------------------------------
    % RadioButton : Mouse (for debugging)
    
    p_movie.count = p_movie.count + 1;
    r_movie_on.x   = p_movie.xpos(p_movie.count);
    r_movie_on.y   = 0.1 ;
    r_movie_on.w   = p_movie.w;
    r_movie_on.h   = 0.8;
    r_movie_on.tag = 'radiobutton_movie_on';
    handles.(r_movie_on.tag) = uicontrol(handles.uipanel_Movie,...
        'Style','radiobutton'                               ,...
        'Units', 'Normalized'                               ,...
        'Position',[r_movie_on.x r_movie_on.y r_movie_on.w r_movie_on.h],...
        'String','On'                                       ,...
        'HorizontalAlignment','Center'                      ,...
        'Tag',r_movie_on.tag                                ,...
        'BackgroundColor',figureBGcolor                     );
    
    
    %% End of opening
    
    % IMPORTANT
    guidata(figHandle,handles)
    % After creating the figure, dont forget the line
    % guidata(figHandle,handles) . It allows smart retrive like
    % handles=guidata(hObject)
    
    % Init with EYELINK Off
    set(handles.uipanel_EyelinkMode,'SelectedObject',handles.radiobutton_EyelinkOff)
    eventdata.NewValue = handles.radiobutton_EyelinkOff;
    GUI.VIEW.SelectionChangeFcn.uipanel_EyelinkMode(handles.uipanel_EyelinkMode, eventdata)
    
    
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%% DEBUG %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if debug
        assignin('base','handles',handles) %#ok<UNRCH>
        disp(handles)
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    figPtr = figHandle;
    
    fprintf('\n')
    fprintf('Response buttons (fORRP 932) : \n')
    fprintf('USB \n')
    fprintf('??? \n')
    fprintf('HID ??? \n')
    fprintf('\n')
    
    
end % creation of figure

if nargout > 0
    
    varargout{1} = guidata(figPtr);
    
end


end % function
