function Draw( self, LR ) 

self.rect = CenterRectArrayOnPoint(...
    [0 0 self.dim self.width]     ,...
    self.(['pos_' LR])            ,...
    self.Y                         ...
    );

Screen('FillRect', self.wPtr, self.color_Active, self.rect);

end % function
