function Draw( self, LR, Color )

self.rect = CenterRectArrayOnPoint(...
    self.rect_Scaled  ,...
    self.(['pos_' LR]),...
    self.pos_Y         ...
    );

Screen('DrawTexture', self.wPtr,  self.(['texPtr_' LR]), [], self.rect,[],[],[],self.(['color_' Color]));

end % function
