function Draw( self, UP, Color )

self.rect = CenterRectArrayOnPoint(...
    [0 0 self.dim self.width],...
    self.pos_X               ,...
    self.(['pos_' UP])        ...
    );

Screen('FillRect', self.wPtr, self.(['color_' Color]), self.rect);

end % function
