function Draw( self, LR, UP, Color )

self.rect = CenterRectArrayOnPoint(...
    [0 0 self.dim self.width],...
    self.(['pos_' LR]),...
    self.(['pos_' UP])...
    );

Screen('FillRect', self.wPtr, self.(['color_' Color]), self.rect);

end % function
